### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by FallenDeity** [Snipy7374/pyweek-sept-2024#9]
This a list of all tasks and milestones to be achieved 

- [x] #10 Adding different classes of enemies in the game [minifolk](https://lyaseek.itch.io/minifhumans)
- [x] #11 Adding a stamina and hp system for both enemies and player
- [x] Creating atleast 15 maps overall
    - [x] #12 Maps using already present tileset by @Stovoy (5 maps)
    - [x] #13 2 more sets of maps 5 each using other tilesets (total 10) - Set 1
    - [x] #14 2 more sets of maps 5 each using other tilesets (total 10) - Set 2
- [x] #15 Adding sound effects for game and bg music
- [x] #16 Adding some form of currency like coins or crystals to collect for score
- [x] #17 Handling menu and game logic for start stop pause reset close game over etc and any settings
- [x] #18 Working on lighting and shadows using shaders for dynamic environments/maps
